Menu dudu2
guilherme-gjv/avaliacao1-2bim-poo pull request #11
Opened 2021-08-27 16:55 UTC by duardoqueiroz

<h2>Algumas coisas feitas: </h2> 

 - <h3> Classe para empréstimo criada, pois facilita o desenvolvimento do sistema;</h3>
 - <h3>Métodos da função principal implementados. </h3>
 - <h3>As classes foram organizadas e os modificadores de acesso foram implementados.</h3>

<h2>PS: Há algumas coisas a serem consertadas</h2>

2021-08-28 03:31 UTC, guilherme-gjv commented
Cara tá perfeito, parabéns
Falta consertar o que?

2021-08-28 03:40 UTC, guilherme-gjv commented
Vou fechar algumas issues inclusive

2021-08-28 14:30 UTC, guilherme-gjv requested changes
Algumas modificações >_<

2021-08-28 14:30 UTC, guilherme-gjv commented on Menu.java
> +            if ((dado.equalsIgnoreCase(livro[j].getCodigo()) || dado.equalsIgnoreCase(livro[j].getTitulo()))
acho que dava pra usar um else{}, fica mais fácil de entender skskskkss

2021-08-28 14:30 UTC, guilherme-gjv commented on Menu.java
>          System.out.println("\nInforme a quantidade de livros que deseja cadastrar: ");
É bom implementar uma 6º opção de adicionar livro/advogado no método exibirMenu(), e não deixar só no início do construtor. Inclusive, o mesmo método poderia ser reutilizado no construtor. Se vc concordar eu posso fazer isso >_<

2021-08-28 21:44 UTC, duardoqueiroz commented on Menu.java
>          System.out.println("\nInforme a quantidade de livros que deseja cadastrar: ");
Seria uma boa, mas n sei se funcionaria nesse código, pois pra adicionar um novo livro/advogado, o tamanho do vetor teria que mudar na hora de criar o objeto, e eu n sei se tem como fazer isso...

2021-08-28 22:10 UTC, guilherme-gjv commented on Menu.java
>          System.out.println("\nInforme a quantidade de livros que deseja cadastrar: ");
compreensível, tenha uma boa noite kkkkkkkkkkkkkkk

2021-08-28 22:12 UTC, guilherme-gjv commented on Menu.java
>          System.out.println("\nInforme a quantidade de livros que deseja cadastrar: ");
pera, dá pra verificar se o espaço é nulo

2021-08-29 04:20 UTC, guilherme-gjv approved these changes

2021-08-29 04:23 UTC, guilherme-gjv commented
**Todos** os campos a seguir foram testados, eu aprovo o merge final :-)

- [x] 1. Exibir Advogados, Livros e Empréstimos.
- [x] 2. Solicitar empréstimo de um livro.
- [x] 3. Devolver livro.
- [x] 4. Trocar Advogado de Departamento.
- [x] 5. Exibir livros emprestados de uma determinada área.
- [x] 6. Registrar Advogado.
- [x] 7. Registrar Livro.
- [x] 0. Sair.

2021-08-29 15:10 UTC, merged